[global]
developmentMode = false

[server]
port = 8501
address = "0.0.0.0"
headless = true
fileWatcherType = "none"
maxUploadSize = 2048
maxMessageSize = 200
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 8501

[theme]
primaryColor = "#28a745"  # Verde para botões primários (era #FF6B6B vermelho)
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[client]
caching = true
displayEnabled = true

[runner]
magicEnabled = true
installTracer = false
fixMatplotlib = true

[logger]
level = "info"
